### ISSUE TITLE
Project maintenance and further plans of development?

### ISSUE THREAD

**Issue by SemyonSinchenko** [pyspark-ai/pyspark-ai#190]
Hello!
The project is very cool, but it looks like it has been facing a lack of maintenance for last four months. It looks like the latest actual commit except just versions bumping was in November. Also, there are no new feature-issues. What are the plans of authors about the project and further development?

I have motivation to contribute. As a start I can try to at least update dependencies, like:
1. Bump Python to `~3.9` because `3.8` is officially legacy and the end of support is October 2024
2. Bum langchain to `~0.1` version (the latest one is `0.1.9`, but the project [uses](https://github.com/pyspark-ai/pyspark-ai/blob/master/poetry.lock#L999) the version `0.0.354`)
3. Bump `openai` to `~1.0` (the latest version of `openai` is `1.13` but the project uses `0.27.10`
4. Try to update the overall code to make it works with the latest `langchain` and `openai`

**Comment by gengliangwang** [comment]
Hi @SemyonSinchenko,
Thanks for bring this up. The dependency updates makes sense, please create PRs and I will review and merge them.
As for the future plans, I am thinking about porting the project into Apache Spark, so that it will be developed and maintained by a much larger community.
As for feature works, there are two items on the top of my mind:
* Python Code generation for DataFrame transforms
* Multiple DataFrame transform support

I am currently focusing on another project, so what I can do now is only review and merge PRs. I will get back to it once I have more time later this year.
